version: '3'

vars:
  BUILD_DIR: build
  PROJECT_NAME: obsidian-tmdb-cover

tasks:
  build:
    desc: Build the CLI after linting and tests
    deps: [test, lint]
    cmds:
      - task: build-go

  build-linux:
    desc: Cross-compile for Linux amd64
    deps: [test, lint]
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - task: build-go

  build-ci:
    desc: Compile only (lint and tests run separately in CI)
    cmds:
      - task: build-go

  test:
    desc: Run the Go test suite
    cmds:
      - task: test-go

  test-ci:
    desc: Run tests with CI tags and coverage
    cmds:
      - task: test-go-ci

  lint:
    desc: Check formatting and run static analysis
    deps: [fmt-check]
    cmds:
      - go vet ./...
      - golangci-lint run

  fmt:
    desc: Format Go sources with goimports
    cmds:
      - task: fmt-go

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - mkdir -p {{.BUILD_DIR}}
      - rm -f coverage.out

  build-go:
    desc: Compile the CLI
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.PROJECT_NAME}} ./cmd/obsidian-tmdb-cover

  test-go:
    desc: Run Go tests
    cmds:
      - go test ./...

  test-go-ci:
    desc: Run Go tests with CI tags and coverage
    cmds:
      - go test -tags=ci -cover -coverprofile=coverage.out -v ./...

  fmt-go:
    desc: Format Go files using goimports
    cmds:
      - goimports -w .

  fmt-check:
    desc: Ensure Go files are already formatted
    cmds:
      - |
        OUT="$(goimports -l .)"
        if [ -n "$OUT" ]; then
          echo "$OUT"
          echo
          echo "Go files require formatting. Run 'task fmt'."
          exit 1
        fi
